config/routes.rb
Rails.application.routes.draw do
  root 'museums#index'
  resources :paintings
  resources :artists do
    resources :paintings, only: :index
  end
  resources :museums do
    resources :paintings, only: :index
  end

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :paintings
end

app/models/museum.rb
class Museum < ActiveRecord::Base
  has_many :paintings
end

app/models/painting.rb
class Painting < ActiveRecord::Base
  belongs_to :artist
  belongs_to :museum

  def self.search(query)
    where('title LIKE :query', query: "%#{query}%")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
end

app/controllers/museums_controller.rb
class MuseumsController < ApplicationController

  def index
    @museums = Museum.all 
  end



end

app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController
  def index
    if params.key? :artist_id
      @paintings = Painting.where(artist_id: params[:artist_id])
    elsif params.key? :museum_id
      @paintings = Painting.where(museum_id: params[:museum_id])
    elsif params.key? :q
      @paintings = Painting.search(params[:q])
    else
      @paintings = Painting.all
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/museums_helper.rb
module MuseumsHelper
end

app/helpers/paintings_helper.rb
module PaintingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MuseumApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/museums/index.html.erb
<h1> Welcome to the Wide World of Museums </h1>

<%= form_tag paintings_path, method: 'GET' do %>
  <%= text_field_tag :q %>
  <%= submit_tag "Search" %>
<% end %>

<table>
  <thead>
    <tr>
      <th>
      </th>
    </tr>
  </thead>

  <tbody>
    <% @museums.each do |museum| %>
      <tr>
        <td><%= link_to museum.name, museum_paintings_path(museum) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'View all paintings', paintings_path %>

app/views/paintings/index.html.erb
<h1>All the Paintings</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Artist</th>
      <th>Style</th>
    </tr>
  </thead>
  <tbody>
    <% @paintings.each do |painting| %>
      <tr>
        <td><%= image_tag painting.image %></td>
        <td><%= painting.title %></td>
        <td><%= link_to painting.artist.name, artist_paintings_path(painting.artist) %></td>
        <td><%= painting.style %></td>
      </tr>
    <% end %>
  </tbody>
</table>